export let farms = [
        {
            id: 0,
            name: "Saint corn",
            location: "New Edem",
            amountOfLivestock: 2000,
            powerOfVents: 100,
            price: 1000,
        },
        {
            id: 1,
            name: "Devil potato",
            location: "New Edem",
            amountOfLivestock: 999,
            powerOfVents: 10000,
            price: 9000,
        },
        {
            id: 2,
            name: "Evil Creature",
            location: "New Edem",
            amountOfLivestock: 10000,
            powerOfVents: 10000,
            price: 7000,
        },
        {
            id: 3,
            name: "Evil Creature",
            location: "New Edem",
            amountOfLivestock: 10000,
            powerOfVents: 10000,
            price: 7000,
        },
        {
            id: 4,
            name: "Evil Creature",
            location: "New Edem",
            amountOfLivestock: 10000,
            powerOfVents: 10000,
            price: 7000,
        },
        {
            id: 5,
            name: "Evil Creature",
            location: "New Edem",
            amountOfLivestock: 10000,
            powerOfVents: 10000,
            price: 7000,
        },
        {
            id: 6,
            name: "Evil Creature",
            location: "New Edem",
            amountOfLivestock: 10000,
            powerOfVents: 10000,
            price: 7000,
        },
        {
            id: 7,
            name: "Evil Creature",
            location: "New Edem",
            amountOfLivestock: 10000,
            powerOfVents: 10000,
            price: 7000,
        }
      ];